<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pet-opoly - The Pet Adoption Game</title>
    <!-- Link to the external CSS file -->
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Main Game Container -->
    <div class="game-container">
        <h1 class="game-title">🐾 PET-OPOLY 🐾</h1>
        <p class="game-subtitle">Adopt pets, build shelters, and become the ultimate pet parent!</p>
        
        <!-- Setup Screen: Initially visible -->
        <div class="setup-screen" id="setupScreen">
            <!-- Section for selecting number of players -->
            <div class="setup-section">
                <h3>🎮 How many players?</h3>
                <div class="player-count-buttons">
                    <button class="count-btn" data-count="2">2 Players</button>
                    <button class="count-btn" data-count="3">3 Players</button>
                    <button class="count-btn selected" data-count="4">4 Players</button>
                </div>
            </div>
            
            <!-- Section for configuring player names and colors -->
            <div class="setup-section">
                <h3>👥 Player Setup</h3>
                <div class="player-setup" id="playerSetup">
                    <!-- Player config cards will be generated by script.js -->
                </div>
            </div>
            
            <!-- Button to start the game -->
            <button class="start-game-btn" id="startBtn">
                🚀 Start Pet-opoly Adventure!
            </button>
        </div>
        
        <!-- Game Screen: Initially hidden -->
        <div class="game-screen" id="gameScreen">
            <!-- The game board will be generated here by script.js -->
            <div class="board" id="board"></div>
            
            <!-- Controls for rolling dice -->
            <div class="game-controls">
                <div class="dice-container">
                    <div class="dice" id="dice1">🎲</div>
                    <div class="dice" id="dice2">🎲</div>
                    <button class="roll-btn" id="rollBtn">Roll Dice</button>
                </div>
            </div>
            
            <!-- Layout for player cards and game stats -->
            <div class="game-layout">
                <div class="player-info" id="playerInfo">
                    <!-- Player cards will be generated here by script.js -->
                </div>
                
                <div class="game-stats">
                    <!-- Card for general game statistics -->
                    <div class="stats-card">
                        <h3>🏆 Game Stats</h3>
                        <div class="stat-item">
                            <span class="stat-label">Turn:</span>
                            <span class="stat-value" id="turnCounter">1</span>
                        </div>
                        <div class="stat-item">
                            <span class="stat-label">Active Players:</span>
                            <span class="stat-value" id="activePlayers">4</span>
                        </div>
                        <div class="stat-item">
                            <span class="stat-label">Money in Play:</span>
                            <span class="stat-value" id="totalMoney">$6000</span>
                        </div>
                    </div>
                    
                    <!-- Card for quick action buttons -->
                    <div class="stats-card">
                        <h3>🎯 Quick Actions</h3>
                        <button class="quick-btn" id="viewPetsBtn">🏠 View All Pets</button>
                        <button class="quick-btn" id="leaderboardBtn">📊 Leaderboard</button>
                        <button class="quick-btn" id="newGameBtn">🔄 New Game</button>
                    </div>
                </div>
            </div>
            
            <!-- Message bar for game updates -->
            <div class="message" id="message">
                Welcome to Pet-opoly!
            </div>
        </div>
    </div>

    <!-- Generic Modal for pop-ups -->
    <div class="modal-overlay" id="genericModal">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-title" id="modalTitle"></div>
            </div>
            <div class="modal-body" id="modalBody"></div>
            <div class="modal-footer" id="modalFooter"></div>
        </div>
    </div>

    <!-- Game Over Modal with Confetti -->
    <div class="modal-overlay game-over-modal" id="gameOverModal">
        <div class="confetti-container" id="confettiContainer"></div>
        <div class="modal-content" style="background: transparent; box-shadow: none; text-align: center;">
             <h2 class="game-over-title">🎉 GAME OVER! 🎉</h2>
             <h3>The winner is...</h3>
             <h1 class="winner-name" id="winnerName"></h1>
             <button class="modal-btn primary" id="playAgainBtn">Play Again</button>
        </div>
    </div>
    
    <!-- Link to the external JavaScript file -->
    <script src="script.js"></script>
</body>
</html>
```

This file now serves as the clean, structural foundation for your game.

Your next step is to create the `style.css` file to add all the visual desi
